apiVersion: apps/v1
kind: Deployment
metadata:
  name: fls-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jetbrains-fls
  template:
    metadata:
      labels:
        app: jetbrains-fls
    spec:
      containers:
      - name: jetbrains-fls
        image: crazymax/jetbrains-license-server:latest
        ports:
        - containerPort: 8000
        env:
        - name: JLS_VIRTUAL_HOSTS
          value: "203.250.34.140"

---
apiVersion: v1
kind: Service
metadata:
  name: jetbrains-service
spec:
  selector:
    app: jetbrains-fls
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
  loadBalancerIP: 203.250.34.140
